resolver: lts-9.0

packages:
- .
- location:
    git: https://github.com/cronburg/AllStar.git
    commit: 15850dd6349740e5c9b7ff391b90d7da2c8537c2
  extra-dep: true

extra-deps: []
flags: {}
extra-package-dbs: []
