#!/bin/bash

#  && stack test ANTLR4:Stacks \

OPTS=--ghc-options="-ddump-splices"

stack test ANTLR4:test-Template $OPTS\
  && stack test ANTLR4:test-ATN $OPTS\
  && stack test ANTLR4:test-G4 $OPTS\
  && stack test ANTLR4:LL1 $OPTS\
  && stack test ANTLR4:LR $OPTS\
  && stack test ANTLR4:lexer $OPTS\
  && stack test ANTLR4:test-Allstar $OPTS\
  && stack test ANTLR4:Chisel $OPTS\

