#!/bin/bash

#  && stack test antlr-haskell:Stacks \

OPTS=--ghc-options="-ddump-splices"

stack test antlr-haskell:Template $OPTS\
  && stack test antlr-haskell:ATN $OPTS\
  && stack test antlr-haskell:CoreG4 $OPTS\
  && stack test antlr-haskell:LL1 $OPTS\
  && stack test antlr-haskell:LR $OPTS\
  && stack test antlr-haskell:lexer $OPTS\
  && stack test antlr-haskell:Allstar $OPTS\
  && stack test antlr-haskell:G4 $OPTS\
  && stack test antlr-haskell:Chisel $OPTS\

